services:
  cache:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        REDIS_PASSWORD: ${REDIS_DEFAULT_PASSWORD}
    ports:
      - ${PORT}:6379

networks:
  default:
    external: true
    name: intranet
