name: CD - Deploy to container registry

on:
  push:
    tags:
      - 'v*'

env:
  C_VERSION: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to docker hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image with :tag
        id: docker_build_tagged
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: dmetzler1988/redis:${{ env.C_VERSION }}
          build-args: |
            "GITHUB_TOKEN=${{ secrets.CONFIGPARSER_TOKEN }}"

      - name: Build image with :latest
        id: docker_build_latest
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: dmetzler1988/redis:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.CONFIGPARSER_TOKEN }}
